### ISSUE TITLE
Failed to activate the rgb package

### ISSUE THREAD

**Issue by averetennikov** [hemanth/atom-rgb#2]
1. Actions: Ctrl+Shift+P -> RGB -> Enter
2. Result:

```
Failed to activate the rgb package
```

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.plugin.activate (C:\Users\username\.atom\packages\rgb\lib\rgb.coffee:9:30)
    at Package.module.exports.Package.activateNow (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\src\package.js:240:19)
    at C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\src\package.js:772:25
    at Emitter.module.exports.Emitter.emit (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:222:20)
    at C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:241:29)
```

Env:
Atom Version: 0.211.0
System: Windows 10 
Thrown From: [rgb](https://github.com/hemanth/atom-rgb) package, v1.0.0

**Comment by hemanth** [comment]
Noticed, the API has been changed, yet to work on it.

**Comment by chrleon** [comment]
Any news on this? Looks like a kickass plugin. Would love to use it.

**Comment by hemanth** [comment]
@chrleon It's already been 2years! Will try to work on this in the weekend.

**Comment by hemanth** [comment]
@antipodeman @chrleon done!
